version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '80:80'
     # - '443:443'
    volumes:
      - '$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf'
     # - '$PWD/nginx/certs:/etc/nginx/certs'
      - '$PWD/nginx/html:/usr/share/nginx/html'
    networks:
      - net 
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
      - net
  db_host:
    container_name: db_host_mysql
    image: mysql:8
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
    ports:
      - "3306:3306"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
networks:
  net: